package com.minidb.server.catalog;

public enum ColumnType {
    SMALLINT, INTEGER, BIGINT, REAL, FLOAT, DOUBLE, DECIMAL, NUMERIC,
    VARCHAR, CHAR, NCHAR, NVARCHAR, BOOLEAN, DATE, TIME, TIMESTAMP,
    BINARY, VARBINARY
}
